# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addCapPushButton_1 = QtWidgets.QPushButton(self.centralWidget)
        self.addCapPushButton_1.setObjectName("addCapPushButton_1")
        self.horizontalLayout.addWidget(self.addCapPushButton_1)
        self.addCapPushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.addCapPushButton_2.setObjectName("addCapPushButton_2")
        self.horizontalLayout.addWidget(self.addCapPushButton_2)
        self.addCapPushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.addCapPushButton_3.setObjectName("addCapPushButton_3")
        self.horizontalLayout.addWidget(self.addCapPushButton_3)
        self.addCapPushButton_4 = QtWidgets.QPushButton(self.centralWidget)
        self.addCapPushButton_4.setObjectName("addCapPushButton_4")
        self.horizontalLayout.addWidget(self.addCapPushButton_4)
        self.addCapPushButton_5 = QtWidgets.QPushButton(self.centralWidget)
        self.addCapPushButton_5.setObjectName("addCapPushButton_5")
        self.horizontalLayout.addWidget(self.addCapPushButton_5)
        self.addCapPushButton_6 = QtWidgets.QPushButton(self.centralWidget)
        self.addCapPushButton_6.setObjectName("addCapPushButton_6")
        self.horizontalLayout.addWidget(self.addCapPushButton_6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("QTabBar::tab{height:17}")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSynchronizeStreams = QtWidgets.QAction(MainWindow)
        self.actionSynchronizeStreams.setCheckable(True)
        self.actionSynchronizeStreams.setObjectName("actionSynchronizeStreams")
        self.actionScaleToFitFrame = QtWidgets.QAction(MainWindow)
        self.actionScaleToFitFrame.setCheckable(True)
        self.actionScaleToFitFrame.setObjectName("actionScaleToFitFrame")
        self.actionFullScreen = QtWidgets.QAction(MainWindow)
        self.actionFullScreen.setCheckable(True)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuOptions.addAction(self.actionSynchronizeStreams)
        self.menuView.addAction(self.actionFullScreen)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.addCapPushButton_1, self.addCapPushButton_2)
        MainWindow.setTabOrder(self.addCapPushButton_2, self.addCapPushButton_3)
        MainWindow.setTabOrder(self.addCapPushButton_3, self.addCapPushButton_4)
        MainWindow.setTabOrder(self.addCapPushButton_4, self.addCapPushButton_5)
        MainWindow.setTabOrder(self.addCapPushButton_5, self.addCapPushButton_6)
        MainWindow.setTabOrder(self.addCapPushButton_6, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "qt-opencv-multithreaded"))
        self.addCapPushButton_1.setText(_translate("MainWindow", "Cap1"))
        self.addCapPushButton_2.setText(_translate("MainWindow", "Cap2"))
        self.addCapPushButton_3.setText(_translate("MainWindow", "Cap3"))
        self.addCapPushButton_4.setText(_translate("MainWindow", "Cap4"))
        self.addCapPushButton_5.setText(_translate("MainWindow", "Cap5"))
        self.addCapPushButton_6.setText(_translate("MainWindow", "Cap6"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSynchronizeStreams.setText(_translate("MainWindow", "Synchronize streams"))
        self.actionScaleToFitFrame.setText(_translate("MainWindow", "Scale to fit frame"))
        self.actionFullScreen.setText(_translate("MainWindow", "Full Screen"))

